backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
  - name: 'aktuelles'
    label: 'Aktuelles'
    folder: 'src/_aktuelles'
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string'}
      - { name: 'date', label: 'Datum', widget: 'date'}
      - { name: 'author', label: 'Autor', widget: 'string'}
      - { name: 'tags', label: 'Tags',  widget: "list", default: ['post']}
      - { name: 'description', label: 'Beschreibung', widget: string }
      - { name: 'image', label: 'Vorschau Bild', widget: image }
      - { name: 'category', label: 'Kategorie', widget: 'select', options: ['Allgemeines', 'AGs', 'Austausche', 'Wettbewerbe', 'Am Schiller'], multiple: true}
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "profil"
    label: "Profil"
    folder: "src/_pages/profil"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "personen"
    label: "Personen"
    folder: "src/_pages/personen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', fields: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "faecher"
    label: "Fächer"
    editor:
      preview: false
    folder: "src/_pages/fächer"
    create: true
    fields:
      - label: 'Generelle Einstellungen'
        name: 'general'
        widget: object
        fields:
          - {name: 'title', label: 'Fach Title', widget: 'string' }
          - {name: 'banner', label: 'Banner', widget: image}
      - label: 'Über das Fach'
        name: 'about'
        widget: object
        fields:
          - {name: 'fachText', label: 'Textblock', widget: 'markdown', required: false}
          - {name: 'fachGallery', label: 'Gallerie', widget: 'list', fields: [{name: 'fachImage', label: 'Bild', widget: 'image'}], required: false }
      - label: 'Die Fachschaft'
        name: 'fachschaft'
        widget: object
        fields:
          - {name: 'fachschaftGallery', label: 'Fachschaftsbilder', widget: 'list', summary: '{{fields.teacherName}}', fields: [{name: 'fachschaftImage', label: 'Bild', widget: 'image'}, {name: 'teacherName', label: Name, widget: string}], required: false }
          - {name: 'teachers', label: 'Lehrer', widget: 'string'}
      - {name: 'contentBlocks', label: 'Weiteres', widget: 'list', types: [ { name: 'title', label: 'Titel Block', widget: 'list', fields: [{ name: 'titleElement', label: 'Titel', widget: 'string'}] }, { name: 'textBlock', label: 'Text Block', widget: 'list', fields: [{ name: 'text', label: 'Text', widget: 'markdown'}] }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'image', label: 'Image', widget: 'image' }] }, { name: 'videoBlock', label: 'Video Block', widget: 'list', fields: [{ name: 'video', label: 'Video', widget: 'object', fields: [{label: 'Platform', name: 'platform', widget: 'select', options: ['Vimeo', 'YouTube']}, {label: 'Link', name: 'link', widget: 'string'}] }] }] }
      - {name: 'tags', label: 'Tags', widget: list, default: ['fach'], required: false}
  - name: "lernen"
    label: "Lernen"
    folder: "src/_pages/lernen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - {name: 'contentBlocks', label: 'Inhalt', widget: 'list', types: [ { name: 'title', label: 'Titel Block', widget: 'list', fields: [{ name: 'titleElement', label: 'Titel', widget: 'string'}] }, { name: 'textBlock', label: 'Text Block', widget: 'list', fields: [{ name: 'text', label: 'Text', widget: 'markdown'}] }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'image', label: 'Image', widget: 'image' }] }, { name: 'videoBlock', label: 'Video Block', widget: 'list', fields: [{ name: 'video', label: 'Video', widget: 'object', fields: [{label: 'Platform', name: 'platform', widget: 'select', options: ['Vimeo', 'YouTube']}, {label: 'Link', name: 'link', widget: 'string'}] }] }] }
      - {name: 'tags', label: 'Tags', widget: list, default: ['lernen', 'page'], required: false}
  - name: "management"
    label: "Management"
    files: 
      - label: 'Einstellungen'
        name: 'settings'
        file: '_data/settings.json'
        fields:
          - label: 'Anmeldephase'
            name: 'anmeldephase'
            widget: 'boolean'
            default: false
          - label: 'Post Einstellungen'
            name: 'posts'
            widget: 'object'
            fields:
              - {label: 'Anzahl der Posts angezeigt auf der Startseite', name: front_limit, widget: 'number'}
              - {label: 'Standard Autor', name: author, widget: string}
          - label: 'Kontakt Einstellungen'
            name: 'contact'
            widget: 'object'
            fields:
              - {label: 'Telefonnummer', name: phone, widget: 'string'}
              - {label: 'E-Mail Adresse', name: email, widget: string}
              - {label: 'Telefax', name: fax, widget: string}
          - label: 'Tags'
            name: 'tags'
            widget: 'list'
            default: ['settings']
            required: false