backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
  - name: 'aktuelles'
    label: 'Aktuelles'
    folder: 'src/_aktuelles'
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string'}
      - { name: 'date', label: 'Datum', widget: 'date'}
      - { name: 'author', label: 'Autor', widget: 'string'}
      - { name: 'description', label: 'Beschreibung', widget: string }
      - { name: 'image', label: 'Vorschau Bild', widget: image }
      - { name: 'category', label: 'Kategorie', widget: 'select', options: ['Allgemeines', 'AGs', 'Austausche', 'Wettbewerbe', 'Am Schiller'], multiple: true}
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "profil"
    label: "Profil"
    folder: "src/_pages/profil"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "personen"
    label: "Personen"
    folder: "src/_pages/personen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "faecher"
    label: "Fächer"
    folder: "src/_pages/fächer"
    create: true
    fields:
      - {name: 'title', label: 'Fach Title', widget: 'string' }
      - {name: 'fachText', label: 'Über das Fach', widget: 'markdown'}
      - {name: 'fachGallery', label: 'Fachschaftsbilder', widget: 'list', fields: [{name: 'image', label: 'Bild', widget: 'image'}] }
      - {name: 'fachschaftText', label: 'Von der Fachschaft', widget: 'markdown'}
      - {name: 'fachschaftGallery', label: 'Fachschaftsbilder', widget: 'list', fields: [{name: 'image', label: 'Bild', widget: 'image'}] }
      - {name: 'studentReviews', label: 'Schüler:innen über Kunst', widget: 'list', fields: [{name: 'review', label: Review, widget: 'markdown'}, {name: 'name', label: 'Name', widget: string}]}
  - name: "lernen"
    label: "Lernen"
    folder: "src/_pages/lernen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  