backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
collections: 
  - name: 'aktuelles'
    label: 'Aktuelles'
    folder: 'src/_aktuelles'
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string'}
      - { name: 'date', label: 'Datum', widget: 'date'}
      - { name: 'author', label: 'Autor', widget: 'string'}
      - { name: 'tags', label: 'Tags',  widget: "list", default: ['post']}
      - { name: 'description', label: 'Beschreibung', widget: string }
      - { name: 'image', label: 'Vorschau Bild', widget: image }
      - { name: 'category', label: 'Kategorie', widget: 'select', options: ['Allgemeines', 'AGs', 'Austausche', 'Wettbewerbe', 'Am Schiller'], multiple: true}
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "profil"
    label: "Profil"
    folder: "src/_pages/profil"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "personen"
    label: "Personen"
    folder: "src/_pages/personen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', fields: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "faecher"
    label: "Fächer"
    editor:
      preview: false
    folder: "src/_pages/fächer"
    create: true
    fields:
      - {name: 'title', label: 'Fach Title', widget: 'string' }
      - {name: 'category', label: 'Kategorie', widget: select, options: ['Naturwissenschaften', 'Gesellschaftswissenschaften', 'Sprachen', 'Weitere']}
      - {name: 'banner', label: 'Banner', widget: image}
      - {name: 'fachText', label: 'Über das Fach', widget: 'markdown', required: false}
      - {name: 'fachGallery', label: 'Fachbilder', widget: 'list', fields: [{name: 'fachImage', label: 'Bild', widget: 'image'}], required: false }
      - {name: 'fachschaftGallery', label: 'Fachschaftsbilder', widget: 'list', summary: '{{fields.teacherName}}', fields: [{name: 'fachschaftImage', label: 'Bild', widget: 'image'}, {name: 'teacherName', label: Name, widget: string}], required: false }
      - {name: 'teachers', label: 'Lehrer', widget: 'string'}
      - {name: 'more', label: 'Weiteres', widget: 'list', types: [ { name: 'text_block', label: 'Text Block', widget: 'list', field: [{ name: 'text', label: 'Text', widget: 'markdown'}] }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'image', label: 'Image', widget: 'image' }] }, { name: 'video', label: 'Video Link', widget: 'string' }] }
      - {name: 'tags', label: 'Tags', widget: list, default: ['fach'], required: false}
  - name: "lernen"
    label: "Lernen"
    folder: "src/_pages/lernen"
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'content_blocks', label: 'Content Blocks', widget: 'list', types: [{ name: 'text_block', label: 'Text Block', widget: 'markdown' }, { name: 'gallery', label: 'Gallery', widget: 'list', fields: [{ name: 'images', label: 'Images', widget: 'list', fields: [{ name: 'image', label: "Image", widget: "image"}] }] }] }
  - name: "management"
    label: 'Management'
    files: 
      - file: '_data/settings.js'
        name: 'settings'
        label: 'Einstellungen'
        fields:
          - {label: 'Anmeldephase', name: 'anmeldephase', widget: 'bool'}